import { ArrowDown, ArrowRight, BrainCircuit, Building2, Database, Eye, Factory, GitBranch, Globe2, Layers3, Map, Network, Satellite, ScanSearch, ShieldCheck, Trees, Waves, Workflow, Zap } from "lucide-react";
import { Panel } from "@/components/Panel";

const dataSources = [{ title: "NASA FIRMS", subtitle: "Near-real-time active fire detections", icon: Satellite, accent: "amber" }, { title: "MODIS / VIIRS", subtitle: "Thermal bands · 375 m active fire product", icon: RadioIcon, accent: "cyan" }, { title: "OpenStreetMap", subtitle: "Infrastructure · roads · land use · facilities", icon: Globe2, accent: "teal" }, { title: "Satellite imagery", subtitle: "Visual context and anomaly corroboration", icon: Eye, accent: "purple" }] as const;
const approach = [{ title: "Detection", detail: "Find thermal anomalies", icon: Satellite }, { title: "Context", detail: "Join geospatial evidence", icon: Map }, { title: "Feature extraction", detail: "Normalize signal behavior", icon: Layers3 }, { title: "Classification", detail: "Rank candidate classes", icon: BrainCircuit }, { title: "GIS visualization", detail: "Make the result actionable", icon: ScanSearch }];
const spatial = [{ label: "Industrial proximity", icon: Factory, value: "Distance to mapped facilities" }, { label: "Land use", icon: Building2, value: "Built-up, agricultural, forest" }, { label: "Vegetation", icon: Trees, value: "Coverage and environmental context" }, { label: "Infrastructure", icon: GitBranch, value: "Roads, pipelines, utility assets" }, { label: "Geographic distribution", icon: Globe2, value: "Regional concentration and spread" }];
const temporal = [{ label: "Detection frequency", value: "How often a signal recurs", icon: Workflow }, { label: "Persistence", value: "Repeated activity at a fixed location", icon: Zap }, { label: "Movement", value: "Spread vector and shifting centroid", icon: Network }, { label: "Spatial expansion", value: "Footprint growth across passes", icon: ScanSearch }, { label: "Historical behavior", value: "Prior detections and recurrence history", icon: Database }];
const architecture = [{ label: "NASA FIRMS API", detail: "Satellite observation ingress", icon: Satellite, tone: "amber" }, { label: "Data Processing", detail: "Clean, normalize, geolocate", icon: Database, tone: "cyan" }, { label: "Feature Engineering", detail: "Spatial · temporal · thermal", icon: Layers3, tone: "teal" }, { label: "Classification Engine", detail: "Evidence-weighted ranking", icon: BrainCircuit, tone: "purple" }, { label: "Geospatial Database", detail: "Events and context layers", icon: Globe2, tone: "cyan" }, { label: "GIS API", detail: "Map and analyst surfaces", icon: Map, tone: "gold" }, { label: "Web Application", detail: "Mission-control interface", icon: Workflow, tone: "coral" }] as const;

function RadioIcon(props: { size?: number; className?: string }) { return <Network {...props} />; }
function SourceCard({ item }: { item: typeof dataSources[number] }) { const colors = { amber: "border-[#76582f] bg-[#2d281c] text-[#efb45b]", cyan: "border-[#28545d] bg-[#102a31] text-[#6ec8c9]", teal: "border-[#2f6768] bg-[#143136] text-[#7bcacc]", purple: "border-[#59436e] bg-[#211b2b] text-[#b394d2]" }; return <div className={`rounded-[3px] border p-4 ${colors[item.accent]}`}><item.icon size={17} /><p className="mt-4 font-display text-[14px] font-semibold text-[#e2eeee]">{item.title}</p><p className="mt-1 font-mono text-[8px] uppercase leading-relaxed tracking-[0.07em] text-[#829ba2]">{item.subtitle}</p></div>; }
function FeatureList({ items }: { items: typeof spatial }) { return <div className="space-y-2">{items.map((item, index) => <div key={item.label} className="flex items-center gap-3 rounded-[3px] border border-[#203d48] bg-[#0d1921] p-3"><span className="font-mono text-[8px] text-[#c39549]">0{index + 1}</span><div className="flex h-8 w-8 items-center justify-center rounded-[3px] border border-[#2d5c64] bg-[#16343a] text-[#73c8ca]"><item.icon size={14} /></div><div><p className="font-display text-[12px] font-semibold text-[#d9e8e9]">{item.label}</p><p className="mt-0.5 font-mono text-[8px] uppercase tracking-[0.06em] text-[#728d96]">{item.value}</p></div></div>)}</div>; }

export default function About() { return <div className="space-y-5 pb-8"><Panel className="overflow-hidden" noPadding accent="amber"><div className="relative p-6 sm:p-9"><div className="absolute -right-20 -top-28 h-80 w-80 rounded-full border border-[#875f2c]/30 bg-[radial-gradient(circle,rgba(217,154,62,0.18),transparent_66%)]" /><div className="absolute right-12 top-10 h-48 w-48 rounded-full border border-[#315b64]/40" /><div className="relative max-w-3xl"><p className="font-mono text-[9px] uppercase tracking-[0.22em] text-[#c39850]">Methodology / THERMAGUARD AI</p><h2 className="mt-4 font-display text-[34px] font-semibold leading-[1.03] tracking-[-0.045em] text-[#e8f2f1] sm:text-[48px]">From thermal signal<br /><span className="text-[#dca149]">to explainable context.</span></h2><p className="mt-5 max-w-2xl text-[14px] leading-relaxed text-[#90a7ad]">The system is designed to help analysts understand what a satellite-detected thermal anomaly might represent by combining observation, geography, history, and uncertainty in one operating picture.</p></div></div></Panel>
    <Panel title="The problem" eyebrow="Why context is necessary"><div className="grid gap-6 lg:grid-cols-[1.05fr_0.95fr] lg:items-center"><div><p className="font-display text-[22px] font-semibold leading-tight text-[#e0ecee]">One bright pixel can describe very different real-world events.</p><p className="mt-4 max-w-2xl text-[13px] leading-relaxed text-[#8ca5ac]">Satellite systems can detect thermal anomalies, but a thermal anomaly is not a classification by itself. The same signal may represent an industrial process, a forest fire, agricultural burning, or a persistent thermal source. Without nearby infrastructure, land-use, temporal behavior, and imagery, the observation remains ambiguous.</p></div><div className="grid grid-cols-3 gap-2"><div className="rounded-[3px] border border-[#713f3a] bg-[#2c2020] p-3 text-center"><FlameIcon /><p className="mt-2 font-mono text-[8px] uppercase text-[#d9917d]">Industrial</p></div><div className="rounded-[3px] border border-[#76582f] bg-[#2d281c] p-3 text-center"><Trees size={17} className="mx-auto text-[#d6b26b]" /><p className="mt-2 font-mono text-[8px] uppercase text-[#d4b879]">Natural</p></div><div className="rounded-[3px] border border-[#2f6768] bg-[#143136] p-3 text-center"><Factory size={17} className="mx-auto text-[#7bcacc]" /><p className="mt-2 font-mono text-[8px] uppercase text-[#7bcacc]">Persistent</p></div></div></div></Panel>
    <Panel title="Data sources" eyebrow="Evidence enters from multiple layers"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{dataSources.map((item) => <SourceCard key={item.title} item={item} />)}</div></Panel>
    <Panel title="Our approach" eyebrow="Observation to decision support"><div className="grid gap-2 md:grid-cols-5">{approach.map((item, index) => <div key={item.title} className="relative"><div className="h-full rounded-[3px] border border-[#2a525d] bg-[#102a31] p-4"><div className="flex items-center justify-between"><item.icon size={16} className="text-[#72c7c9]" /><span className="font-mono text-[8px] text-[#6f8992]">0{index + 1}</span></div><p className="mt-4 font-display text-[13px] font-semibold text-[#dcebec]">{item.title}</p><p className="mt-1 font-mono text-[8px] uppercase tracking-[0.06em] text-[#76919a]">{item.detail}</p></div>{index < approach.length - 1 && <ArrowRight size={14} className="absolute -right-3 top-1/2 z-10 hidden -translate-y-1/2 text-[#d6a04d] md:block" />}{index < approach.length - 1 && <ArrowDown size={14} className="mx-auto my-1 text-[#d6a04d] md:hidden" />}</div>)}</div></Panel>
    <div className="grid gap-5 xl:grid-cols-2"><Panel title="Spatial features" eyebrow="Where is the signal?" action={<Map size={14} className="text-[#6fc4c6]" />}><FeatureList items={spatial} /></Panel><Panel title="Temporal features" eyebrow="How does the signal behave?" action={<Workflow size={14} className="text-[#d5a04d]" />}><FeatureList items={temporal} /></Panel></div>
    <Panel title="Explainable classification" eyebrow="Evidence behind every result"><div className="grid gap-6 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)] lg:items-center"><div className="rounded-[3px] border border-[#2f666a] bg-[#143139] p-5"><div className="flex items-start gap-3"><ShieldCheck size={20} className="mt-0.5 text-[#7bcacc]" /><div><p className="font-display text-[17px] font-semibold text-[#e1eeee]">No black-box result</p><p className="mt-2 text-[12px] leading-relaxed text-[#a7c2c5]">Every classification is accompanied by the evidence that pushed it toward one class and away from another. Analysts can inspect signal strength, context, persistence, and uncertainty before acting.</p></div></div></div><div className="space-y-3">{[["Industrial infrastructure", "92%", "Strong nearby facility and built-up context"], ["Temporal persistence", "87%", "Repeated detections across satellite passes"], ["Vegetation context", "18%", "Low support for a forest or agricultural explanation"]].map(([label, value, detail]) => <div key={label}><div className="flex items-center justify-between font-mono text-[9px]"><span className="text-[#9ab1b6]">{label}</span><span className="text-[#d7a24e]">{value}</span></div><div className="mt-1 h-1.5 rounded-full bg-[#1b333c]"><div className="h-full rounded-full bg-[#66c3c4]" style={{ width: value }} /></div><p className="mt-1 font-mono text-[8px] uppercase tracking-[0.06em] text-[#69858e]">{detail}</p></div>)}</div></div></Panel>
    <Panel title="Technical architecture" eyebrow="From NASA observation to web application"><div className="grid gap-2 md:grid-cols-7">{architecture.map((item, index) => <div key={item.label} className="relative"><div className={`h-full rounded-[3px] border p-3 ${item.tone === "amber" ? "border-[#76582f] bg-[#2d281c]" : item.tone === "purple" ? "border-[#59436e] bg-[#211b2b]" : item.tone === "coral" ? "border-[#713f3a] bg-[#2c2020]" : "border-[#28545d] bg-[#102a31]"}`}><div className="flex items-center justify-between"><item.icon size={15} className={item.tone === "amber" ? "text-[#efb45b]" : item.tone === "purple" ? "text-[#b394d2]" : item.tone === "coral" ? "text-[#e98772]" : "text-[#6ec8c9]"} /><span className="font-mono text-[8px] text-[#6e8992]">0{index + 1}</span></div><p className="mt-3 font-display text-[11px] font-semibold leading-tight text-[#dbe9ea]">{item.label}</p><p className="mt-1 font-mono text-[8px] uppercase leading-relaxed tracking-[0.05em] text-[#78939b]">{item.detail}</p></div>{index < architecture.length - 1 && <ArrowRight size={13} className="absolute -right-2.5 top-1/2 z-10 hidden -translate-y-1/2 text-[#d6a04d] md:block" />}{index < architecture.length - 1 && <ArrowDown size={13} className="mx-auto my-1 text-[#d6a04d] md:hidden" />}</div>)}</div><div className="mt-4 flex items-center gap-2 border-t border-[#1d3843] pt-3 font-mono text-[8px] uppercase tracking-[0.1em] text-[#6d8891]"><ShieldCheck size={12} className="text-[#71c6c7]" /> Frontend foundation uses realistic mock data; live ingestion and persistence are reserved for the next implementation phase.</div></Panel>
  </div>; }
function FlameIcon() { return <Zap size={17} className="mx-auto text-[#e98772]" />; }
