import { Activity, BarChart3, Download, Factory, Flame, Gauge, Globe2, Layers3, Radio, Satellite, Target, Zap } from "lucide-react";
import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis, Area, AreaChart } from "recharts";
import { Button } from "@/components/Button";
import { ChartContainer } from "@/components/ChartContainer";
import { Panel } from "@/components/Panel";
import { classificationMeta } from "@/lib/mockData";
import { toast } from "sonner";

type Range = "24 Hours" | "7 Days" | "30 Days" | "Custom";
const ranges: Range[] = ["24 Hours", "7 Days", "30 Days", "Custom"];
const palette = { industrial: "#ef6b57", natural: "#f4a64d", agricultural: "#c7b766", persistent: "#57b8c6", unclassified: "#8793a5" };
const tooltipStyle = { background: "#12232c", border: "1px solid #315666", borderRadius: 3, fontFamily: "IBM Plex Mono", fontSize: 10 };

const rangeConfig: Record<Range, { factor: number; labels: string[]; caption: string }> = {
  "24 Hours": { factor: 0.12, labels: ["00:00", "04:00", "08:00", "12:00", "16:00", "20:00", "24:00"], caption: "Last orbital cycle" },
  "7 Days": { factor: 0.54, labels: ["29 Aug", "30 Aug", "31 Aug", "01 Sep", "02 Sep", "03 Sep", "06 Sep"], caption: "Seven-day observation window" },
  "30 Days": { factor: 1, labels: ["06 Aug", "10 Aug", "14 Aug", "18 Aug", "22 Aug", "26 Aug", "30 Aug", "06 Sep"], caption: "Thirty-day observation window" },
  Custom: { factor: 1.25, labels: ["06 Jul", "13 Jul", "20 Jul", "27 Jul", "03 Aug", "10 Aug", "17 Aug", "24 Aug", "31 Aug"], caption: "Custom analyst window" },
};

function scale(value: number, factor: number, index: number) { return Math.round(value * factor * (0.92 + ((index * 7) % 11) / 100)); }
function Metric({ label, value, note, icon: Icon, tone = "cyan" }: { label: string; value: string; note: string; icon: typeof Activity; tone?: "cyan" | "amber" | "coral" | "gold" }) { const colors = { cyan: "#62c1c3", amber: "#e3ab52", coral: "#ed765f", gold: "#c8b667" }; return <div className="border-l border-[#31545f] bg-[#0d1921] p-4" style={{ boxShadow: `inset 2px 0 ${colors[tone]}55` }}><Icon size={15} style={{ color: colors[tone] }} /><p className="mt-3 font-mono text-[8px] uppercase tracking-[0.13em] text-[#6e8992]">{label}</p><p className="mt-1 font-display text-[22px] font-semibold text-[#e0edef]">{value}</p><p className="mt-1 font-mono text-[8px] uppercase tracking-[0.08em] text-[#657f89]">{note}</p></div>; }

function DensityMap({ factor }: { factor: number }) { const points = [{ x: 58, y: 44, r: 18, c: palette.natural, n: 218 }, { x: 69, y: 47, r: 10, c: palette.industrial, n: 142 }, { x: 76, y: 53, r: 12, c: palette.persistent, n: 216 }, { x: 45, y: 58, r: 16, c: palette.natural, n: 302 }, { x: 83, y: 62, r: 11, c: palette.agricultural, n: 129 }, { x: 50, y: 77, r: 13, c: palette.natural, n: 188 }, { x: 38, y: 66, r: 8, c: palette.industrial, n: 68 }, { x: 62, y: 71, r: 8, c: palette.persistent, n: 94 }]; return <div className="relative h-[300px] overflow-hidden rounded-[3px] border border-[#294d58] bg-[#0a1b23]"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-0 h-full w-full"><defs><pattern id="geoGrid" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M8 0H0V8" fill="none" stroke="#39717a" strokeWidth=".18" opacity=".5" /></pattern><filter id="blurDensity"><feGaussianBlur stdDeviation="2.2" /></filter></defs><rect width="100" height="100" fill="url(#geoGrid)" /><path d="M5 32 C19 17 32 20 39 30 S53 32 62 22 S76 20 89 29 L94 44 L85 52 L93 66 L76 74 L62 69 L52 81 L36 76 L25 84 L13 68 L4 63 Z" fill="#143943" stroke="#4a8187" strokeWidth=".35" opacity=".85" /><path d="M5 32 C19 17 32 20 39 30 S53 32 62 22 S76 20 89 29 L94 44 L85 52 L93 66 L76 74 L62 69 L52 81 L36 76 L25 84 L13 68 L4 63 Z" fill="none" stroke="#8ab8ae" strokeWidth=".25" strokeDasharray="1.4 1.8" opacity=".5" /><path d="M0 46 C20 38 34 48 48 43 S72 37 100 47 M0 67 C19 59 34 70 50 63 S77 56 100 67" fill="none" stroke="#72a5a7" strokeWidth=".25" opacity=".35" />{points.map((point) => <g key={`${point.x}-${point.y}`}><circle cx={point.x} cy={point.y} r={point.r / 2.1} fill={point.c} opacity=".08" filter="url(#blurDensity)" /><circle cx={point.x} cy={point.y} r={point.r / 5} fill={point.c} opacity={0.18 + factor * 0.1} /><circle cx={point.x} cy={point.y} r={1.1} fill={point.c} /></g>)}</svg><div className="absolute left-4 top-4 flex items-center gap-2 rounded-[3px] border border-[#37636c] bg-[#0b2028]/90 px-3 py-2 font-mono text-[8px] uppercase tracking-[0.13em] text-[#9bc4c7]"><Globe2 size={12} className="text-[#72c6c8]" /> Global density / normalized</div><div className="absolute bottom-4 left-4 flex flex-wrap gap-3 font-mono text-[8px] uppercase tracking-[0.1em] text-[#718d96]"><span className="flex items-center gap-1"><span className="h-1.5 w-1.5 rounded-full" style={{ background: palette.natural }} /> Natural</span><span className="flex items-center gap-1"><span className="h-1.5 w-1.5 rounded-full" style={{ background: palette.industrial }} /> Industrial</span><span className="flex items-center gap-1"><span className="h-1.5 w-1.5 rounded-full" style={{ background: palette.persistent }} /> Persistent</span></div><div className="absolute bottom-4 right-4 font-mono text-[8px] uppercase tracking-[0.1em] text-[#d4a24e]">Signal intensity ↑</div></div>; }

export default function Analytics() {
  const [range, setRange] = useState<Range>("7 Days");
  const config = rangeConfig[range];
  const factor = config.factor;
  const eventTrend = useMemo(() => config.labels.map((label, index) => ({ label, industrial: scale([48, 62, 71, 86, 104, 96, 122, 138, 154][index % 9], factor, index), natural: scale([132, 146, 168, 154, 184, 176, 202, 226, 248][index % 9], factor, index + 2), agricultural: scale([26, 34, 38, 42, 47, 53, 58, 64, 70][index % 9], factor, index + 4), persistent: scale([38, 42, 49, 52, 61, 67, 72, 79, 86][index % 9], factor, index + 6) })), [config.labels, factor]);
  const distribution = useMemo(() => [{ name: "Natural / Forest", value: scale(743, factor, 2), color: palette.natural }, { name: "Persistent industrial", value: scale(216, factor, 4), color: palette.persistent }, { name: "Industrial fire", value: scale(142, factor, 6), color: palette.industrial }, { name: "Agricultural", value: scale(129, factor, 8), color: palette.agricultural }, { name: "Unclassified", value: scale(54, factor, 10), color: palette.unclassified }], [factor]);
  const frpData = useMemo(() => [{ name: "Industrial", value: Number((27.8 * (0.88 + factor * 0.12)).toFixed(1)), color: palette.industrial }, { name: "Natural", value: Number((34.6 * (0.91 + factor * 0.09)).toFixed(1)), color: palette.natural }, { name: "Agricultural", value: Number((18.1 * (0.94 + factor * 0.06)).toFixed(1)), color: palette.agricultural }, { name: "Persistent", value: Number((39.7 * (0.96 + factor * 0.04)).toFixed(1)), color: palette.persistent }], [factor]);
  const confidenceData = useMemo(() => [{ band: "95–100", events: scale(212, factor, 1) }, { band: "90–94", events: scale(318, factor, 2) }, { band: "80–89", events: scale(446, factor, 3) }, { band: "70–79", events: scale(218, factor, 4) }, { band: "<70", events: scale(90, factor, 5) }], [factor]);
  const persistenceData = useMemo(() => config.labels.map((label, index) => ({ label, revisits: Math.round((3 + Math.sin(index * 1.7) * 1.5 + index * 0.45) * (0.75 + factor * 0.25)), industrial: Math.round((1.2 + index * 0.34) * (0.76 + factor * 0.24)) })), [config.labels, factor]);
  const distanceData = useMemo(() => [{ distance: 0.8, frp: 42, class: "Persistent" }, { distance: 1.2, frp: 27, class: "Industrial" }, { distance: 2.4, frp: 35, class: "Industrial" }, { distance: 4.8, frp: 19, class: "Agricultural" }, { distance: 8.7, frp: 31, class: "Natural" }, { distance: 14.2, frp: 37, class: "Natural" }, { distance: 18.6, frp: 22, class: "Agricultural" }, { distance: 31.4, frp: 12, class: "Unclassified" }].map((point) => ({ ...point, frp: Number((point.frp * (0.78 + factor * 0.22)).toFixed(1)) })), [factor]);
  const totals = { total: distribution.reduce((sum, entry) => sum + entry.value, 0), industrial: distribution[2].value, natural: distribution[0].value, persistent: distribution[1].value, avgFrp: (frpData.reduce((sum, entry) => sum + entry.value, 0) / frpData.length).toFixed(1), avgConfidence: Math.round(84 + factor * 4) };
  const exportBrief = () => { const brief = `THERMAGUARD AI — ANALYTICAL BRIEF\nObservation window: ${range}\nTotal events: ${totals.total}\nIndustrial events: ${totals.industrial}\nNatural fires: ${totals.natural}\nPersistent sources: ${totals.persistent}\nAverage FRP: ${totals.avgFrp} MW\nAverage confidence: ${totals.avgConfidence}%\n\nPrototype data for demonstration only.`; const blob = new Blob([brief], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `thermaguard-${range.toLowerCase().replaceAll(" ", "-")}-brief.txt`; anchor.click(); URL.revokeObjectURL(url); toast.success("Analytical brief downloaded"); };
  return <div className="space-y-5 pb-8">
    <div className="flex flex-col justify-between gap-4 border-b border-[#1d3542] pb-5 lg:flex-row lg:items-end"><div><p className="font-mono text-[9px] uppercase tracking-[0.2em] text-[#d29c49]">Analytical brief / orbital signal review</p><h2 className="mt-2 font-display text-[27px] font-semibold tracking-[-0.03em] text-[#e4eff0]">Thermal analytics</h2><p className="mt-2 max-w-2xl text-[13px] text-[#7b969e]">Confidence-weighted anomaly behavior across classification, persistence, intensity, and infrastructure context.</p></div><div className="flex flex-wrap items-center gap-2">{ranges.map((item) => <button key={item} type="button" onClick={() => setRange(item)} className={`rounded-[3px] border px-3 py-2 font-mono text-[9px] font-semibold uppercase tracking-[0.12em] transition ${range === item ? "border-[#c59043] bg-[#493720] text-[#efbb67] shadow-[0_0_16px_rgba(205,145,58,0.1)]" : "border-[#294754] bg-[#0d1921] text-[#78929b] hover:border-[#4e7c86] hover:text-[#d0e0e2]"}`}>{item}</button>)}<Button variant="outline" size="md" onClick={exportBrief}><Download size={13} /> Export brief</Button></div></div>
    <div className="flex items-center justify-between rounded-[3px] border border-[#2d555f] bg-gradient-to-r from-[#102b32] via-[#0f222a] to-[#111d24] px-4 py-3"><div className="flex items-center gap-3"><div className="rounded-[3px] border border-[#3e7376] bg-[#173e43] p-2 text-[#7ed0d0]"><Satellite size={15} /></div><div><p className="font-mono text-[9px] uppercase tracking-[0.16em] text-[#83b8bc]">Window active / {config.caption}</p><p className="mt-1 text-[12px] text-[#b9ced0]">Signal population recalculated for the selected observation range.</p></div></div><div className="hidden items-center gap-2 font-mono text-[9px] uppercase tracking-[0.12em] text-[#729099] sm:flex"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#74c8c9]" /> Live query</div></div>
    <div className="grid gap-px overflow-hidden rounded-[3px] border border-[#294652] bg-[#294652] sm:grid-cols-2 xl:grid-cols-6"><Metric label="Total events" value={totals.total.toLocaleString()} note={`${range} window`} icon={Activity} tone="cyan" /><Metric label="Industrial events" value={totals.industrial.toLocaleString()} note="classified industrial" icon={Factory} tone="coral" /><Metric label="Natural fires" value={totals.natural.toLocaleString()} note="forest / natural" icon={Flame} tone="amber" /><Metric label="Persistent sources" value={totals.persistent.toLocaleString()} note="repeat signatures" icon={Radio} tone="cyan" /><Metric label="Average FRP" value={`${totals.avgFrp} MW`} note="across detections" icon={Zap} tone="gold" /><Metric label="Average confidence" value={`${totals.avgConfidence}%`} note="classifier confidence" icon={Gauge} tone="cyan" /></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(330px,0.75fr)]"><ChartContainer title="Thermal events over time" eyebrow={`Classification volume / ${range}`} action={<span className="font-mono text-[9px] uppercase tracking-[0.1em] text-[#6d8992]">Events / interval</span>}><div className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={eventTrend} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><CartesianGrid stroke="#1e3945" vertical={false} strokeDasharray="3 3" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#718a93", fontSize: 9, fontFamily: "IBM Plex Mono" }} dy={8} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "#718a93", fontSize: 9, fontFamily: "IBM Plex Mono" }} /><Tooltip contentStyle={tooltipStyle} /><Line type="monotone" dataKey="industrial" name="Industrial" stroke={palette.industrial} strokeWidth={2} dot={false} /><Line type="monotone" dataKey="natural" name="Natural" stroke={palette.natural} strokeWidth={2} dot={false} /><Line type="monotone" dataKey="agricultural" name="Agricultural" stroke={palette.agricultural} strokeWidth={2} dot={false} /><Line type="monotone" dataKey="persistent" name="Persistent" stroke={palette.persistent} strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div></ChartContainer><ChartContainer title="Classification distribution" eyebrow="Composition of classified detections"><div className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={distribution} dataKey="value" nameKey="name" innerRadius={68} outerRadius={98} paddingAngle={3} stroke="#101b24" strokeWidth={4}>{distribution.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip contentStyle={tooltipStyle} /><text x="50%" y="46%" textAnchor="middle" dominantBaseline="middle" fill="#e2edef" fontSize="24" fontFamily="Space Grotesk" fontWeight="600">{totals.total.toLocaleString()}</text><text x="50%" y="55%" textAnchor="middle" dominantBaseline="middle" fill="#708b94" fontSize="9" fontFamily="IBM Plex Mono">EVENTS</text></PieChart></ResponsiveContainer></div><div className="flex flex-wrap justify-center gap-x-4 gap-y-2">{distribution.map((entry) => <span key={entry.name} className="flex items-center gap-1.5 font-mono text-[8px] uppercase tracking-[0.08em] text-[#7d969d]"><span className="h-1.5 w-1.5 rounded-full" style={{ background: entry.color }} />{entry.name}</span>)}</div></ChartContainer></div>
    <div className="grid gap-5 xl:grid-cols-3"><ChartContainer title="Average fire radiative power" eyebrow="FRP / megawatts by classification"><div className="h-[260px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={frpData} margin={{ top: 5, right: 8, left: -24, bottom: 0 }}><CartesianGrid stroke="#1e3945" vertical={false} strokeDasharray="3 3" /><XAxis dataKey="name" tickLine={false} axisLine={false} tick={{ fill: "#718a93", fontSize: 8, fontFamily: "IBM Plex Mono" }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "#718a93", fontSize: 8, fontFamily: "IBM Plex Mono" }} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="value" name="Average FRP" radius={[2, 2, 0, 0]}>{frpData.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Bar></BarChart></ResponsiveContainer></div></ChartContainer><ChartContainer title="Classification confidence" eyebrow="Confidence band distribution"><div className="h-[260px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={confidenceData} layout="vertical" margin={{ top: 5, right: 8, left: 6, bottom: 0 }}><CartesianGrid stroke="#1e3945" horizontal={false} /><XAxis type="number" tickLine={false} axisLine={false} tick={{ fill: "#718a93", fontSize: 8, fontFamily: "IBM Plex Mono" }} /><YAxis dataKey="band" type="category" width={50} tickLine={false} axisLine={false} tick={{ fill: "#9db1b7", fontSize: 8, fontFamily: "IBM Plex Mono" }} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="events" name="Events" fill="#65bdc1" radius={[0, 2, 2, 0]} barSize={15} /></BarChart></ResponsiveContainer></div></ChartContainer><ChartContainer title="Event persistence" eyebrow="Mean revisits across the selected range"><div className="h-[260px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={persistenceData} margin={{ top: 8, right: 8, left: -24, bottom: 0 }}><defs><linearGradient id="persistFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#a987d1" stopOpacity={0.32} /><stop offset="100%" stopColor="#a987d1" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#1e3945" vertical={false} strokeDasharray="3 3" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#718a93", fontSize: 8, fontFamily: "IBM Plex Mono" }} interval={1} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "#718a93", fontSize: 8, fontFamily: "IBM Plex Mono" }} /><Tooltip contentStyle={tooltipStyle} /><Area type="monotone" dataKey="revisits" name="Mean revisits" stroke="#a987d1" fill="url(#persistFill)" strokeWidth={2} /></AreaChart></ResponsiveContainer></div></ChartContainer></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]"><ChartContainer title="Distance to industrial infrastructure" eyebrow="FRP against nearest mapped facility"><div className="h-[290px]"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{ top: 10, right: 8, left: -18, bottom: 0 }}><CartesianGrid stroke="#1e3945" strokeDasharray="3 3" /><XAxis type="number" dataKey="distance" name="Distance" unit=" km" tickLine={false} axisLine={false} tick={{ fill: "#718a93", fontSize: 8, fontFamily: "IBM Plex Mono" }} /><YAxis type="number" dataKey="frp" name="FRP" unit=" MW" tickLine={false} axisLine={false} tick={{ fill: "#718a93", fontSize: 8, fontFamily: "IBM Plex Mono" }} /><ZAxis range={[45, 130]} /><Tooltip cursor={{ strokeDasharray: "3 3" }} contentStyle={tooltipStyle} /><Scatter name="Detections" data={distanceData} fill="#62c1c3"><Cell fill="#ef6b57" /></Scatter></ScatterChart></ResponsiveContainer></div><div className="flex items-center justify-between border-t border-[#1d3742] pt-3 font-mono text-[9px] uppercase tracking-[0.1em] text-[#708b94]"><span className="flex items-center gap-2"><Target size={12} className="text-[#d8a04b]" /> Closer assets correlate with persistent signatures</span><span className="text-[#d6a04d]">r = −0.64</span></div></ChartContainer><ChartContainer title="Geographic distribution" eyebrow="Confidence-weighted global density"><DensityMap factor={factor} /></ChartContainer></div>
    <div className="flex items-center gap-2 border-t border-[#1d3542] pt-4 font-mono text-[9px] uppercase tracking-[0.12em] text-[#667f89]"><Layers3 size={12} className="text-[#d7a049]" /> Derived from FIRMS detections, infrastructure context, and classifier evidence · {config.caption}</div>
  </div>;
}
