import { Activity, ArrowDown, ArrowRight, BrainCircuit, CheckCircle2, Flame, GitBranch, Layers3, MapPin, Orbit, Radio, Satellite, ScanSearch, ShieldCheck, Trees, Waves, Zap } from "lucide-react";
import { useMemo, useState } from "react";
import { Panel } from "@/components/Panel";
import { Button } from "@/components/Button";
import { ClassificationBadge } from "@/components/ClassificationBadge";
import { thermalEvents, type Classification, type ThermalEvent } from "@/lib/mockData";

type Probability = { label: string; value: number; color: string };
const probabilitySets: Record<string, Probability[]> = {
  "FRM-2026-0906-004": [{ label: "Industrial Fire", value: 91, color: "#ef6b57" }, { label: "Natural Fire", value: 5, color: "#f4a64d" }, { label: "Agricultural Burning", value: 2, color: "#c7b766" }, { label: "Persistent Source", value: 2, color: "#57b8c6" }],
  "FRM-2026-0906-001": [{ label: "Persistent Source", value: 88, color: "#57b8c6" }, { label: "Industrial Fire", value: 8, color: "#ef6b57" }, { label: "Natural Fire", value: 2, color: "#f4a64d" }, { label: "Agricultural Burning", value: 2, color: "#c7b766" }],
  "FRM-2026-0906-002": [{ label: "Natural Fire", value: 86, color: "#f4a64d" }, { label: "Agricultural Burning", value: 7, color: "#c7b766" }, { label: "Industrial Fire", value: 4, color: "#ef6b57" }, { label: "Persistent Source", value: 3, color: "#57b8c6" }],
  "FRM-2026-0906-003": [{ label: "Agricultural Burning", value: 79, color: "#c7b766" }, { label: "Natural Fire", value: 12, color: "#f4a64d" }, { label: "Industrial Fire", value: 5, color: "#ef6b57" }, { label: "Persistent Source", value: 4, color: "#57b8c6" }],
};

const evidenceBase = [{ label: "Thermal Intensity", icon: Flame }, { label: "Spatial Concentration", icon: ScanSearch }, { label: "Industrial Proximity", icon: Orbit }, { label: "Temporal Persistence", icon: Activity }, { label: "Vegetation Context", icon: Trees }];
const sourceInputs = [{ label: "FIRMS data", detail: "FRP · brightness · confidence", icon: Flame, tone: "amber" }, { label: "OSM context", detail: "Facilities · roads · land use", icon: MapPin, tone: "cyan" }, { label: "Satellite evidence", detail: "VIIRS thermal composite", icon: Satellite, tone: "teal" }, { label: "Historical behavior", detail: "Recurrence · persistence", icon: Radio, tone: "purple" }] as const;

function Pipeline() { return <Panel title="Classification pipeline" eyebrow="Multi-source evidence fusion"><div className="space-y-3"><div className="grid gap-2 sm:grid-cols-4">{sourceInputs.map((item, index) => <div key={item.label} className={`relative rounded-[3px] border p-3 ${item.tone === "amber" ? "border-[#76582f] bg-[#2d281c]" : item.tone === "purple" ? "border-[#59436e] bg-[#211b2b]" : "border-[#28545d] bg-[#102a31]"}`}><div className="flex items-center justify-between"><item.icon size={15} className={item.tone === "amber" ? "text-[#efb45b]" : item.tone === "purple" ? "text-[#b394d2]" : "text-[#6ec8c9]"} /><span className="font-mono text-[8px] text-[#6e8992]">0{index + 1}</span></div><p className="mt-3 font-display text-[12px] font-semibold text-[#dbe9ea]">{item.label}</p><p className="mt-1 font-mono text-[8px] uppercase tracking-[0.06em] text-[#78939b]">{item.detail}</p></div>)}</div><div className="flex items-center justify-center gap-2 py-1 text-[#d6a04d]"><span className="h-px flex-1 bg-[#315963]" /><span className="font-mono text-[8px] uppercase tracking-[0.16em]">Feature extraction</span><ArrowDown size={14} /><span className="h-px flex-1 bg-[#315963]" /></div><div className="grid gap-3 sm:grid-cols-2"><div className="flex items-center gap-3 rounded-[3px] border border-[#315c65] bg-[#112d34] p-4"><div className="rounded-[3px] border border-[#4d8589] bg-[#1b4a4e] p-2.5 text-[#7bced0]"><Layers3 size={17} /></div><div><p className="font-display text-[14px] font-semibold text-[#e1eeee]">Feature extraction</p><p className="mt-1 font-mono text-[8px] uppercase tracking-[0.08em] text-[#7da5aa]">37 contextual signals normalized</p></div></div><div className="flex items-center gap-3 rounded-[3px] border border-[#684f39] bg-[#2d251c] p-4"><div className="rounded-[3px] border border-[#936d3d] bg-[#4a3820] p-2.5 text-[#efbb67]"><BrainCircuit size={17} /></div><div><p className="font-display text-[14px] font-semibold text-[#e1eeee]">Classification engine</p><p className="mt-1 font-mono text-[8px] uppercase tracking-[0.08em] text-[#b99b68]">Calibrated evidence weighting</p></div></div></div><div className="flex items-center justify-center gap-2 py-1 text-[#d6a04d]"><span className="h-px flex-1 bg-[#315963]" /><ArrowDown size={14} /><span className="font-mono text-[8px] uppercase tracking-[0.16em]">Explainable result</span><span className="h-px flex-1 bg-[#315963]" /></div></div></Panel>; }

function ProbabilityPanel({ probabilities }: { probabilities: Probability[] }) { return <Panel title="Classification probabilities" eyebrow="Relative likelihood across candidate classes"><div className="space-y-4">{probabilities.map((item, index) => <div key={item.label}><div className="mb-1.5 flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="font-mono text-[9px] text-[#607b85]">0{index + 1}</span><span className="font-mono text-[10px] text-[#b3c6ca]">{item.label}</span></div><span className="font-display text-[17px] font-semibold" style={{ color: item.color }}>{item.value}%</span></div><div className="h-2 overflow-hidden rounded-full bg-[#1a3038]"><div className="h-full rounded-full transition-all duration-300" style={{ width: `${item.value}%`, background: item.color, boxShadow: `0 0 13px ${item.color}66` }} /></div></div>)}</div><div className="mt-5 flex items-start gap-2 border-t border-[#203d48] pt-4"><ShieldCheck size={14} className="mt-0.5 shrink-0 text-[#72c8c9]" /><p className="font-mono text-[9px] leading-relaxed text-[#78939b]">Probabilities are calibrated mock outputs for interface demonstration; they express relative evidence support, not certainty.</p></div></Panel>; }

function EvidencePanel({ event }: { event: ThermalEvent }) { const values = useMemo(() => [{ label: "Thermal Intensity", value: Math.min(98, Math.round(event.brightness / 4)), icon: Flame, color: "#ef765e" }, { label: "Spatial Concentration", value: event.classification === "Industrial Fire" ? 90 : 82, icon: ScanSearch, color: "#65c3c5" }, { label: "Industrial Proximity", value: event.classification.includes("Industrial") ? 92 : 24, icon: Orbit, color: "#d6a24e" }, { label: "Temporal Persistence", value: event.classification.includes("Persistent") ? 94 : event.classification === "Industrial Fire" ? 87 : 78, icon: Activity, color: "#a987d1" }, { label: "Vegetation Context", value: event.classification.includes("Natural") ? 91 : 18, icon: Trees, color: "#7eb37f" }], [event]); return <Panel title="Evidence strength" eyebrow="Signals contributing to the result"><div className="space-y-4">{values.map((item) => <div key={item.label}><div className="mb-1.5 flex items-center justify-between"><div className="flex items-center gap-2"><item.icon size={13} style={{ color: item.color }} /><span className="font-mono text-[10px] text-[#a7bbc0]">{item.label}</span></div><span className="font-mono text-[11px] font-semibold" style={{ color: item.color }}>{item.value}%</span></div><div className="h-2 overflow-hidden rounded-full bg-[#1a3038]"><div className="h-full rounded-full" style={{ width: `${item.value}%`, background: item.color }} /></div></div>)}</div></Panel>; }

export default function ClassificationIntelligence() { const [selectedId, setSelectedId] = useState("FRM-2026-0906-004"); const event = thermalEvents.find((item) => item.id === selectedId) ?? thermalEvents[3]; const probabilities = probabilitySets[event.id] ?? probabilitySets["FRM-2026-0906-004"]; const top = probabilities[0]; const explanation = event.classification === "Industrial Fire" ? "High thermal intensity, strong spatial concentration, and close proximity to heavy industrial infrastructure drive the industrial-fire result. Low vegetation context reduces support for a natural or agricultural explanation." : event.classification.includes("Natural") ? "High vegetation context and clustered spatial behavior provide stronger support for a natural-fire result than for an industrial source." : "The combined evidence favors a context-specific thermal source, while the remaining probability mass reflects uncertainty across nearby classes."; return <div className="space-y-5 pb-8"><div className="flex flex-col justify-between gap-4 border-b border-[#1d3542] pb-5 lg:flex-row lg:items-end"><div><p className="font-mono text-[9px] uppercase tracking-[0.2em] text-[#d29c49]">Mission control / explainable classifier</p><h2 className="mt-2 font-display text-[27px] font-semibold tracking-[-0.03em] text-[#e4eff0]">Evidence fusion workspace</h2><p className="mt-2 max-w-2xl text-[13px] text-[#7b969e]">A multi-source evidence view for understanding how thermal anomalies are classified without reducing the decision to a single prediction.</p></div><div className="flex items-center gap-2"><span className="h-2 w-2 animate-pulse rounded-full bg-[#65c4c5]" /><span className="font-mono text-[9px] uppercase tracking-[0.13em] text-[#8eb6b8]">Inference workspace</span></div></div>
    <div className="flex flex-col gap-3 rounded-[3px] border border-[#315762] bg-[#0e222b] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[0.16em] text-[#d29c49]">Interactive sample event</p><p className="mt-1 font-display text-[16px] font-semibold text-[#dcebed]">Inspect how evidence changes the classification outcome</p></div><label className="flex items-center gap-3"><span className="font-mono text-[8px] uppercase tracking-[0.14em] text-[#78929a]">Event</span><select value={selectedId} onChange={(eventChange) => setSelectedId(eventChange.target.value)} className="h-9 min-w-[260px] rounded-[3px] border border-[#365e68] bg-[#0b171f] px-3 font-mono text-[9px] text-[#c7d9db] outline-none focus:border-[#67c5c6]">{thermalEvents.slice(0, 4).map((item) => <option key={item.id} value={item.id}>{item.id} · {item.location}</option>)}</select></label></div>
    <Pipeline />
    <div className="grid gap-5 xl:grid-cols-[minmax(0,0.82fr)_minmax(0,1.18fr)]"><Panel title="Selected event" eyebrow="FIRMS anomaly under review"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><Zap size={15} className="text-[#e2a34d]" /><p className="font-mono text-[10px] font-semibold text-[#dba44f]">{event.id}</p></div><h3 className="mt-2 font-display text-[21px] font-semibold text-[#e2edef]">{event.location}</h3><p className="mt-1 flex items-center gap-1.5 font-mono text-[9px] uppercase tracking-[0.08em] text-[#718b94]"><MapPin size={11} /> {event.country} · {event.coordinates}</p></div><ClassificationBadge classification={event.classification} /></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["FRP", `${event.frp} MW`], ["Brightness", `${event.brightness} K`], ["Confidence", `${event.confidence}%`], ["Satellite", event.satellite.split(" /")[0]]].map(([label, value]) => <div key={label} className="border-l border-[#bb8d43] pl-3"><p className="font-mono text-[8px] uppercase tracking-[0.1em] text-[#6d8891]">{label}</p><p className="mt-1 font-mono text-[10px] leading-relaxed text-[#d5e4e5]">{value}</p></div>)}</div></Panel><ProbabilityPanel probabilities={probabilities} /></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,0.95fr)_minmax(0,1.05fr)]"><EvidencePanel event={event} /><Panel title="Classification explanation" eyebrow="Evidence-weighted reasoning"><div className="rounded-[3px] border border-[#2e666b] bg-[#143139] p-5"><div className="flex items-start gap-3"><div className="rounded-[3px] border border-[#3f7c80] bg-[#1b4a4e] p-2.5 text-[#7ed0d0]"><CheckCircle2 size={18} /></div><div><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-[#7bcacc]">Explainable result</p><p className="mt-2 font-display text-[22px] font-semibold text-[#e3eeee]">{top.label.toUpperCase()}</p><p className="mt-3 text-[13px] leading-relaxed text-[#a6c2c5]">{explanation}</p></div></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{[["Evidence sources", "6 integrated"], ["Signals evaluated", "37 features"], ["Calibration", "Evidence-weighted"]].map(([label, value]) => <div key={label} className="rounded-[3px] border border-[#24444f] bg-[#0d1921] p-3"><p className="font-mono text-[8px] uppercase tracking-[0.1em] text-[#6c8790]">{label}</p><p className="mt-1 font-mono text-[10px] text-[#d4e3e4]">{value}</p></div>)}</div><p className="mt-4 border-t border-[#274750] pt-3 font-mono text-[9px] leading-relaxed text-[#718b94]">This interface communicates a ranked, uncertainty-aware classification result. It does not claim perfect accuracy; final operational decisions require analyst review and corroborating evidence.</p></Panel></div>
  </div>;
}
