import { ArrowLeft, Building2, CalendarDays, CheckCircle2, Factory, Flame, GitBranch, LocateFixed, Map, MapPin, Navigation, Radio, Ruler, Satellite, Trees, Waves, Zap } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link, useRoute } from "wouter";
import { Button } from "@/components/Button";
import { ClassificationBadge } from "@/components/ClassificationBadge";
import { Panel } from "@/components/Panel";
import { RiskScore } from "@/components/RiskScore";
import { ThermalFingerprint } from "@/components/ThermalFingerprint";
import { thermalEvents, type ThermalEvent } from "@/lib/mockData";
import { getRiskAssessment, getThermalFingerprint } from "@/services/thermaguardService";

const timeline = [
  { day: "06 Aug", detections: 0, frp: 0 }, { day: "08 Aug", detections: 1, frp: 18 }, { day: "10 Aug", detections: 0, frp: 0 }, { day: "12 Aug", detections: 2, frp: 31 }, { day: "14 Aug", detections: 1, frp: 24 }, { day: "16 Aug", detections: 0, frp: 0 }, { day: "18 Aug", detections: 2, frp: 39 }, { day: "20 Aug", detections: 1, frp: 22 }, { day: "22 Aug", detections: 0, frp: 0 }, { day: "24 Aug", detections: 2, frp: 35 }, { day: "26 Aug", detections: 1, frp: 27 }, { day: "28 Aug", detections: 2, frp: 41 }, { day: "30 Aug", detections: 1, frp: 29 }, { day: "02 Sep", detections: 2, frp: 43 }, { day: "06 Sep", detections: 3, frp: 43 },
];

const evidence = [
  { label: "Industrial Infrastructure", value: 92, color: "#63c3c5" },
  { label: "Temporal Persistence", value: 87, color: "#63c3c5" },
  { label: "Spatial Concentration", value: 90, color: "#63c3c5" },
  { label: "Vegetation Context", value: 18, color: "#d5a04b" },
  { label: "Thermal Intensity", value: 81, color: "#d5a04b" },
];

function SatelliteEvidence({ event }: { event: ThermalEvent }) {
  return <div className="relative h-[330px] overflow-hidden rounded-[3px] border border-[#355b62] bg-[#1b2b22]">
    <div className="absolute inset-0 opacity-90" style={{ backgroundImage: "linear-gradient(135deg, rgba(112,122,63,.65), transparent 33%), linear-gradient(30deg, transparent 40%, rgba(54,86,57,.75) 41%, transparent 42%), linear-gradient(145deg, transparent 55%, rgba(156,127,60,.52) 55%, rgba(156,127,60,.52) 58%, transparent 58%), radial-gradient(circle at 62% 42%, rgba(223,141,50,.5), transparent 15%), linear-gradient(180deg,#233c36,#263d28 48%,#4c4c2a)" }} />
    <div className="absolute inset-0 opacity-35" style={{ backgroundImage: "linear-gradient(rgba(215,203,131,.12) 1px, transparent 1px), linear-gradient(90deg, rgba(215,203,131,.12) 1px, transparent 1px)", backgroundSize: "24px 24px" }} />
    <svg viewBox="0 0 900 360" className="absolute inset-0 h-full w-full opacity-70"><path d="M0 288 C120 234 184 266 294 208 S521 242 660 162 S809 193 900 114" fill="none" stroke="#bcc477" strokeWidth="2" opacity=".44" /><path d="M48 42 L180 340 M280 0 L380 360 M548 0 L458 360 M770 0 L650 360" stroke="#dbca84" strokeWidth="1.2" strokeDasharray="5 7" opacity=".34" /><path d="M0 128 L900 247 M0 302 L900 55" stroke="#172a25" strokeWidth="10" opacity=".36" /></svg>
    <div className="absolute left-[61%] top-[42%] flex -translate-x-1/2 -translate-y-1/2 items-center justify-center"><span className="absolute h-28 w-28 animate-pulse rounded-full border border-[#ffbf58]/35" /><span className="absolute h-16 w-16 rounded-full border border-[#ffbf58]/70" /><span className="h-3 w-3 rounded-full bg-[#ffb548] shadow-[0_0_24px_8px_rgba(255,173,63,.58)]" /></div>
    <div className="absolute left-4 top-4 flex items-center gap-2 rounded-[3px] border border-[#6a784d] bg-[#15251c]/85 px-3 py-2 font-mono text-[8px] uppercase tracking-[0.14em] text-[#d8dcaf]"><Satellite size={12} className="text-[#e0a34d]" /> VIIRS thermal composite / simulated</div>
    <div className="absolute bottom-4 left-4 font-mono text-[8px] uppercase tracking-[0.13em] text-[#d1d5a1]">{event.coordinates} · 375 m pixel</div><div className="absolute bottom-4 right-4 rounded-[3px] border border-[#8d5d36] bg-[#442d20]/80 px-2 py-1 font-mono text-[8px] uppercase tracking-[0.12em] text-[#ffc16a]">Anomaly highlighted</div>
  </div>;
}

function GISContext({ event }: { event: ThermalEvent }) {
  return <div className="relative h-[330px] overflow-hidden rounded-[3px] border border-[#355b62] bg-[#0e2730]"><div className="absolute inset-0 opacity-60" style={{ backgroundImage: "linear-gradient(rgba(76,153,159,.16) 1px, transparent 1px), linear-gradient(90deg, rgba(76,153,159,.16) 1px, transparent 1px)", backgroundSize: "30px 30px" }} /><svg viewBox="0 0 700 360" className="absolute inset-0 h-full w-full"><path d="M0 82 C124 110 174 26 275 82 S431 158 534 81 S637 44 700 77" fill="none" stroke="#6eabb0" strokeWidth="2" opacity=".4" /><path d="M-30 260 C110 198 214 280 335 217 S525 150 730 218" fill="none" stroke="#c0aa68" strokeWidth="2" strokeDasharray="8 6" opacity=".66" /><path d="M100 350 L203 8 M315 350 L368 0 M530 350 L470 0" fill="none" stroke="#7d8f8f" strokeWidth="2" strokeDasharray="4 7" opacity=".46" /><path d="M0 170 C110 147 245 196 340 151 S550 98 720 165" fill="none" stroke="#4c829a" strokeWidth="32" opacity=".24" /><rect x="407" y="112" width="84" height="56" rx="3" fill="#75919a" opacity=".25" stroke="#91c6c7" strokeWidth="1" /><rect x="535" y="205" width="54" height="38" rx="2" fill="#75919a" opacity=".2" stroke="#91c6c7" strokeWidth="1" /></svg><div className="absolute left-[59%] top-[44%] flex -translate-x-1/2 -translate-y-1/2 items-center justify-center"><span className="absolute h-24 w-24 rounded-full border border-[#ef9e55]/40" /><span className="h-3 w-3 rounded-full bg-[#ef9e55] shadow-[0_0_16px_5px_rgba(239,158,85,.5)]" /></div><span className="absolute left-[68%] top-[28%] rounded-full bg-[#7ccac8] p-1.5 text-[#0d2227]"><Factory size={12} /></span><span className="absolute left-[74%] top-[66%] rounded-full bg-[#a987d1] p-1.5 text-[#171324]"><GitBranch size={12} /></span><span className="absolute left-[41%] top-[72%] rounded-full bg-[#8bbbd0] p-1.5 text-[#11232b]"><Waves size={12} /></span><div className="absolute left-4 top-4 flex items-center gap-2 rounded-[3px] border border-[#346570] bg-[#0c2028]/90 px-3 py-2 font-mono text-[8px] uppercase tracking-[0.14em] text-[#a5ced0]"><Map size={12} className="text-[#77c8ca]" /> Context layers / active</div><div className="absolute bottom-4 left-4 flex flex-wrap gap-3 font-mono text-[8px] uppercase tracking-[0.1em] text-[#789da3]"><span className="flex items-center gap-1"><span className="h-1.5 w-1.5 rounded-full bg-[#77c8ca]" /> Facility</span><span className="flex items-center gap-1"><span className="h-1.5 w-1.5 rounded-full bg-[#a987d1]" /> Pipeline</span><span className="flex items-center gap-1"><span className="h-1.5 w-1.5 rounded-full bg-[#8bbbd0]" /> Water</span></div></div>;
}

export default function ThermalEventIntelligence() {
  const [, params] = useRoute("/event/:id");
  const event = thermalEvents.find((item) => item.id === params?.id) ?? thermalEvents[0];
  return <div className="space-y-5 pb-8">
    <div className="flex flex-col justify-between gap-4 border-b border-[#1d3542] pb-5 lg:flex-row lg:items-end"><div><Link href="/events" className="mb-4 inline-flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.14em] text-[#79bfc3] transition hover:text-white"><ArrowLeft size={13} /> Back to event registry</Link><p className="font-mono text-[9px] uppercase tracking-[0.22em] text-[#d29c49]">Selected anomaly / event intelligence</p><h2 className="mt-2 font-display text-[26px] font-semibold tracking-[-0.03em] text-[#e5eff0]">THERMAL EVENT <span className="text-[#dda54e]">#{event.id}</span></h2><p className="mt-2 text-[13px] text-[#78929b]">{event.location} · {event.country} · {event.coordinates}</p></div><div className="flex flex-wrap items-center gap-2"><ClassificationBadge classification={event.classification} /><span className="rounded-[3px] border border-[#2d666c] bg-[#17353b] px-3 py-2 font-mono text-[9px] font-semibold uppercase tracking-[0.13em] text-[#7bcacc]">Confidence: {event.confidence}%</span><span className="rounded-[3px] border border-[#803e3b] bg-[#482727] px-3 py-2 font-mono text-[9px] font-semibold uppercase tracking-[0.13em] text-[#ff9c87]">Priority: HIGH</span></div></div>
    <div className="grid gap-5 xl:grid-cols-[0.72fr_1.28fr]"><Panel title="Risk assessment" eyebrow="Prototype prioritization / 0–100"><RiskScore assessment={getRiskAssessment(event)} /><div className="mt-5 grid grid-cols-2 gap-2">{getRiskAssessment(event).factors.slice(0, 4).map((factor) => <div key={factor.label} className="rounded-[3px] border border-[#203c47] bg-[#0d1921] p-3"><p className="font-mono text-[8px] uppercase tracking-[0.08em] text-[#6f8993]">{factor.label}</p><p className="mt-1 font-mono text-[11px] text-[#dbe8e9]">{factor.value}/{factor.max}</p></div>)}</div></Panel><Panel title="Thermal fingerprint" eyebrow="Composite event signal"><ThermalFingerprint items={getThermalFingerprint(event)} /></Panel></div>

    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.05fr)_minmax(360px,0.95fr)]"><Panel title="Thermal evidence" eyebrow="Signal characteristics / VIIRS 375 m"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["FRP", `${event.frp} MW`, Zap, "text-[#dca149]"], ["Brightness temperature", `${event.brightness} K`, ThermometerIcon, "text-[#e56f58]"], ["Detection confidence", `${event.confidence}%`, CheckCircle2, "text-[#65c3c5]"], ["Detection frequency", "18 passes", Radio, "text-[#a987d1]"]].map(([label, value, Icon, color]) => <div key={label as string} className="rounded-[3px] border border-[#254450] bg-[#0d1921] p-4"><Icon size={15} className={color as string} /><p className="mt-4 font-mono text-[8px] uppercase tracking-[0.1em] text-[#6c8790]">{label as string}</p><p className="mt-1 font-display text-[19px] font-semibold text-[#e0edef]">{value as string}</p></div>)}</div><div className="mt-4 flex items-center justify-between border-t border-[#1d3742] pt-4 font-mono text-[9px] uppercase tracking-[0.1em] text-[#6d8791]"><span className="flex items-center gap-2"><CalendarDays size={12} /> Last detection {event.detectedAt}</span><span className="text-[#78c7c8]">Model v0.8.4</span></div></Panel><Panel title="Spatial evidence" eyebrow="Context around detection"><div className="grid grid-cols-2 gap-x-6 gap-y-4">{[["Distance to industrial facility", "1.2 km", Ruler], ["Land-use type", "Heavy industrial", Building2], ["Vegetation coverage", "18%", Trees], ["Nearby roads", "3 within 500 m", Navigation], ["Nearby infrastructure", "7 assets", Factory], ["Detection centroid", event.coordinates, LocateFixed]].map(([label, value, Icon]) => <div key={label as string} className="flex items-start gap-2.5"><Icon size={14} className="mt-0.5 shrink-0 text-[#76bec0]" /><div><p className="font-mono text-[8px] uppercase tracking-[0.11em] text-[#6c8790]">{label as string}</p><p className="mt-1 font-mono text-[10px] leading-relaxed text-[#d2e1e3]">{value as string}</p></div></div>)}</div></Panel></div>

    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(340px,0.9fr)]"><Panel title="Temporal evidence" eyebrow="30-day detection timeline" action={<span className="font-mono text-[9px] uppercase tracking-[0.1em] text-[#d6a04c]">Recurring signature</span>}><div className="h-[270px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={timeline} margin={{ top: 8, right: 8, left: -22, bottom: 0 }}><defs><linearGradient id="eventTimeline" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#dba04b" stopOpacity={0.38} /><stop offset="100%" stopColor="#dba04b" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#1e3945" vertical={false} strokeDasharray="3 3" /><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{ fill: "#728b94", fontSize: 8, fontFamily: "IBM Plex Mono" }} dy={8} interval={2} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "#728b94", fontSize: 8, fontFamily: "IBM Plex Mono" }} /><Tooltip contentStyle={{ background: "#12222c", border: "1px solid #315666", borderRadius: 3, fontFamily: "IBM Plex Mono", fontSize: 10 }} /><Area type="stepAfter" dataKey="frp" name="FRP / MW" stroke="#dba04b" fill="url(#eventTimeline)" strokeWidth={2} /><Area type="stepAfter" dataKey="detections" name="Detections" stroke="#65bec2" fill="transparent" strokeWidth={1.5} /></AreaChart></ResponsiveContainer></div><div className="flex items-center gap-4 border-t border-[#1d3742] pt-3 font-mono text-[9px] uppercase tracking-[0.1em] text-[#738d96]"><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#dba04b]" /> FRP / MW</span><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#65bec2]" /> Detection count</span><span className="ml-auto text-[#d8a04b]">15 active days</span></div></Panel><Panel title="Satellite evidence" eyebrow="Anomaly location / contextual composite"><SatelliteEvidence event={event} /></Panel></div>

    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.08fr)_minmax(0,0.92fr)]"><Panel title="GIS context" eyebrow="Nearby assets and land-use layers"><GISContext event={event} /><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{[["Industrial facilities", Factory, "3"], ["Roads", Navigation, "3"], ["Buildings", Building2, "24"], ["Pipelines", GitBranch, "2"], ["Water bodies", Waves, "1"]].map(([label, Icon, value]) => <div key={label as string} className="flex items-center gap-2 rounded-[3px] border border-[#203b47] bg-[#0d1921] px-3 py-2.5"><Icon size={12} className="text-[#79c4c5]" /><div><p className="font-mono text-[8px] uppercase tracking-[0.06em] text-[#73909a]">{label as string}</p><p className="mt-1 font-mono text-[10px] text-[#d2e2e3]">{value as string} nearby</p></div></div>)}</div></Panel><Panel title="Why this classification?" eyebrow="Explainable AI evidence"><div className="space-y-4">{evidence.map((item) => <div key={item.label}><div className="mb-1.5 flex items-center justify-between gap-3"><span className="font-mono text-[10px] text-[#a4b8bd]">{item.label}</span><span className="font-mono text-[11px] font-semibold" style={{ color: item.color }}>{item.value}%</span></div><div className="h-2 overflow-hidden rounded-full bg-[#1a3039]"><div className="h-full rounded-full transition-all" style={{ width: `${item.value}%`, background: item.color, boxShadow: `0 0 10px ${item.color}66` }} /></div></div>)}<div className="mt-6 rounded-[3px] border border-[#2d666c] bg-[#15333a] p-4"><div className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.16em] text-[#7bcacc]"><CheckCircle2 size={13} /> Overall classification</div><p className="mt-2 font-display text-xl font-semibold text-[#e3eff0]">INDUSTRIAL FIRE</p><p className="mt-3 text-[12px] leading-relaxed text-[#a4c0c3]">The anomaly is strongly associated with industrial infrastructure and a concentrated, recurring spatial signature. Its low vegetation context and elevated thermal intensity make a natural or agricultural explanation less likely.</p></div></div></Panel></div>
  </div>;
}

function ThermometerIcon(props: { size?: number; className?: string }) { return <Flame {...props} />; }
